### ISSUE TITLE
How to show Image along with post content in home page?

### ISSUE THREAD

**Issue by Fierythunder** [cotes2020/jekyll-theme-chirpy#358] opened 2021-07-06 15:58 UTC
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I want to add image on leftside of post content in the home page 

In previous version this code was helpful
```
<div class="row"> 
  <div class="col-md-10">
    <h1>
      <a href="{{ post.url | relative_url }}">{{ post.title }}</a>
    </h1>
    <div class="post-content">
      {% if post.image.src %}
        <img width="35%" style="margin-top:10px; margin-bottom:10px; margin-right:10px;" src="{{ post.image.src }}" class="pull-left img-responsive" alt="{{ post.title | default: "Preview Image" }}">
      {% endif %}
      <p>
        {% include no-linenos.html content=post.content %}
        {{ content | markdownify | strip_html | truncate: 200 }}
      </p>
    </div>
  </div>
</div>
```
But after updating to latest master branch the text is now present below the image

**Comment by cotes2020** [comment] 2021-07-06 17:52
Duplicate of #327

**Closed** 2021-07-06 17:56 UTC
Labels: question

**Comment by ankit0183** [comment] 2022-11-26 14:18
<a href="{{ post.url | relative_url }}">
          <img style="margin-top:10px; margin-bottom:10px;" src="{{post.image}}"  width="500" align="center" />
        </a>

Hi You have to just put this code into layout hope it will work
