### ISSUE TITLE
作者大大能否添加Valine评论系统

### ISSUE THREAD

**Issue by J-StrawHat** [cotes2020/jekyll-theme-chirpy#262] opened 2021-01-19 07:42 UTC
## Checklist

- [x] I have read the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/.github/CONTRIBUTING.md).
- [x] There are no similar request on existing issues (including closed ones).
- [x] I have read the [project progress](https://github.com/cotes2020/jekyll-theme-chirpy/projects) and know the current progress of the project.
- [x] I was in the `master` branch of the latest code.

## Is your feature request related to a problem? Please describe

尽管Disqus很棒，但在国内如果要评论就需要翻墙才能显示。我的朋友希望在我的博客中留下评论，但每一次评论就需要翻墙，这样下来会十分不方便。😔

## Describe the solution you'd like

看了其他的评论系统，目前来说，[Valine](https://valine.js.org/)是国内相对好用的评论系统，而且UI和chirpy主题一样地简洁。
![Valine](https://gitee.com/j__strawhat/MyImages/raw/master/img/20210119154045.png)
由于自己比较菜，添加了代码推送上Github后还是不能显示出来。希望作者大大能够考虑一下，为我们添加这个可选的评论系统。

**Comment by cotes2020** [comment] 2021-01-23 12:41
Duplicate of #22

**Closed** 2021-01-23 12:41 UTC
Labels: duplicate, enhancement, wontfix
