### ISSUE TITLE
Pages under /posts/ not being indexed

### ISSUE THREAD

**Issue by KKamJi98** [cotes2020/jekyll-theme-chirpy#1876] opened 2024-07-25 16:45 UTC
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

My Jekyll blog pages under /posts/ (e.g., kkamji.net/post/cka, kkamji.net/post/test) are not being indexed by search engines. Pages such as kkamji.net/about, kkamji.net/archives are indexed correctly.

### Steps To Reproduce

https://github.com/KKamJi98/kkamji98.github.io
https://kkamji.net/
https://kkamji.net/sitemap.xml
https://kkamji.net/robots.txt

![image](https://github.com/user-attachments/assets/c7ac6870-90d3-47fe-9ed9-2a247c63a449)
![image](https://github.com/user-attachments/assets/14681426-61c1-4f96-9a37-cb8d4a01ef0e)

### Expected Behavior

Pages under /posts/ should be indexed by search engines.

### Environment

- Ruby: ruby 3.2.3
- Jekyll: jekyll 4.3.3
- Chirpy: * jekyll-theme-chirpy (7.0.1)

### Anything else?

I have verified robots.txt and sitemap.xml are correctly configured.

**Comment by kungfux** [comment] 2024-07-27 18:37
You're lucky. Not everyone gets even 4 indexed pages.

I have 2 pages indexed by Google after 6 months. Meanwhile, Bing had no problems indexing 33 pages. So, it's up to Google, I guess.

See this [discussion](https://github.com/cotes2020/jekyll-theme-chirpy/discussions/1514) related to that problem.

**Comment by cotes2020** [comment] 2024-07-28 06:12
Duplicate of #1176

**Closed by cotes2020** 2024-07-28 06:12 UTC
