### ISSUE TITLE
Non-pinned posts not shown in home

### ISSUE THREAD

**Issue by count-null** [cotes2020/jekyll-theme-chirpy#308] opened 2021-04-07 19:47 UTC
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar reports on existing issues (including closed ones).
- [x] I found the bug on the latest code of `master` branch.

## Describe the bug

Non pinned posts do not show in the home page.

### To Reproduce

Install the theme using the instructions
Create a post
Notice that it only shows on Home if pinned

### Expected behavior

Recent posts should show under "Pinned" in the home page

### Software

- Ruby version: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
- Gem version: 3.1.2
- Bundler version: Bundler version 2.2.15
- Jekyll version: jekyll (4.2.0)

### Additional context

This issue was reported in #305 but was removed for not meeting the template. IMO, the strict template enforcement is unnecessary when the issue is so obvious.

**Comment by cotes2020** [comment] 2021-04-08 06:22
Duplicate of #218

> ... IMO, the strict template enforcement is unnecessary when the issue is so obvious.

The checklist of issue templates is a guide for the questioner to self-treat (many issues are invalid or repeated). And the operation details and soft environment are crucial for the maintainer to quickly locate the problem. Hope you can understand.

**Comment by cotes2020** [comment] 2021-04-08 06:25
Duplicate of #218

**Closed** 2021-04-08 06:27 UTC
Labels: invalid
