### ISSUE TITLE
layout: home # Index page issue

### ISSUE THREAD

**Issue by vkalvakotamath** [cotes2020/jekyll-theme-chirpy#990] opened 2023-04-16 17:44 UTC
Ok so I think some people have asked this previously, but not from as bad a place as mine. I have little idea of using GitHub, and I am using my browser to create and commit files. The issue is that everytime I work on something and I open up my g-pages (https://vkalvakotamath.github.io), it ends up showing a blank page except for --- layout: home # Index page ---. How do I resolve this? Further, I also cannot see posts I wrote -- I have one post I had written, and the home page is somehow absolutely empty, or I must be missing something. If I could have some help that would be great!

**Comment by cotes2020** [comment] 2023-04-16 17:54
Duplicate of #968

**Closed by cotes2020** 2023-04-16 17:54 UTC
Labels: question
