### ISSUE TITLE
Visual text glitches in the sidebar that disappear on hover

### ISSUE THREAD

**Issue by jeertmans** [cotes2020/jekyll-theme-chirpy#1608] opened 2024-03-14 12:15 UTC
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

Hello,

I am not sure if this is a bug from your theme, or from something else (e.g., Chrome, Jekyll, ...), but there are visual glitches in the sidebar (both on my website and on your demo website):

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/27275099/e9370553-f23a-4464-8ac7-b1f56611361a)

They only disappear when I hover over the text.

### Steps To Reproduce

1. Go to your website (I am using Chrome)

### Expected Behavior

No bug

### Environment

Just went to your website as of today: https://chirpy.cotes.page/.

### Anything else?

My website, in the case it helps: https://eertmans.be/.

**Comment by kungfux** [comment] 2024-03-14 19:37
I cannot reproduce it on Windows, either with Chrome 122.0.6261.129 (Official Build) (64-bit) or with Edge. Any other details?

**Comment by cotes2020** [comment] 2024-03-14 21:40
Duplicate of #1268

**Closed** 2024-03-22 23:36 UTC
Labels: duplicate

**Comment by jeertmans** [comment] 2024-03-26 09:19
Sorry for the late reply @kungfux, I didn't have access to the "faulty" computer before today.
Maybe my chrome got updated, but I cannot reproduce it now :-/

Indeed, it looks like this is an error from the Chrome version rather than from this theme, so closing this is fine.
