### ISSUE TITLE
At deployment (via github pages) website just shows --- layout: home # Index page ---, whereas working fine on local machine

### ISSUE THREAD

**Issue by sukhjinder-kumar** [cotes2020/jekyll-theme-chirpy#968] opened 2023-04-07 19:29 UTC
I am new to open source, and this is my first issue. My apologies if I am not able to provide fuller details.

## Describe the bug

I am using the chirpy starter template. I cloned ("generated" is the word)  the repo around 4 days back. I first faced the issue 2 days ago. Everything would be working fine in the local run, however when I push code to GitHub (I am using GitHub pages with a custom domain name), after completion of actions the deployed website would just show  --- layout: home # Index page ---. I don't think it is an error with the code base in particular for I added a few words here and there in a post, pushed it again and it went away.

**Edit:** I made a new commit, and added some more words (17th commit on my repo) in one of the posts. Pushed the code to GitHub, and the issue is gone again.

## To Reproduce

You can find my repo at sukhjinder-kumar/blog over at GitHub. Their deployed website on the 16th commit shows the above error. You can find my website at sukhjinderkumar.me/blog

## Logs/Screenshots
![Screenshot from 2023-04-08 00-52-22](https://user-images.githubusercontent.com/82507694/230665491-7fbd25d8-ca51-4654-a61e-e0b1c823c152.png)

## Environment

The error seems to be at the time of deployment. But the following are versions on my machine

| Command                           | Version |
|-----------------------------------|---------|
| `ruby -v`                         |     3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]    |
| `gem -v`                          |      3.3.5   |
| `bundle -v`                       |    Bundler version 2.4.10     |
| `bundle exec jekyll -v`           |    jekyll 4.3.2   |
| `bundle info jekyll-theme-chirpy` |    * jekyll-theme-chirpy (5.6.1)    |

### Desktop

- OS: Ubuntu 22.04
- Browser: Chrome Version 111.0.5563.146 (Official Build) (64-bit)

**Comment by Venompool888** [comment] 2023-04-08 14:22
Same after clone or fork,but run well [Using the Chirpy Starter](https://chirpy.cotes.page/posts/getting-started/#option-1-using-the-chirpy-starter)

**Comment by sukhjinder-kumar** [comment] 2023-04-09 16:53
Yes, it almost always works fine, but sometimes the GitHub deployed build shows the aforementioned error. Works fine on the local machine (as I wrote earlier). I shared a screenshot and the code (16th commit over at sukhjinder-kumar/blog, not sure if it is reproducible as works on my local machine).

**Comment by cotes2020** [comment] 2023-04-09 22:29
> I am new to open source, ...

Since you put it that way, please consider the following article as your map for exploring the open source community in the future.

http://www.catb.org/~esr/faqs/smart-questions.html

**Comment by sukhjinder-kumar** [comment] 2023-04-11 09:41
Thank you for the insightful reference. I now see my faults while raising the issue, it already existed in solved issues. Will take care in the future.

**Comment by danielmacuare** [comment] 2023-04-13 19:56
Hi @cotes2020 Thanks for this beautiful theme! Great work, I'm loving it.

Would you consider updating the FAQs for this issue? I recently came across the same problem as the one described in this issue.

I read all the Docs in the [Wiki](https://github.com/cotes2020/jekyll-theme-chirpy/wiki)  including the FAQs and I still couldn't find the fix for my problem.

The only solution that helped me was [this one](https://github.com/cotes2020/jekyll-theme-chirpy/issues/502#issuecomment-1060960024). Thanks to @CompetitiveLin for the info.

Based on the comment above, what I did was:
- Created a new branch called `prod`
- Updated my GHA workflow here `.github/workflows/pages-deploy.yml` to point to the new branch `prod`
- Went to my repository and updated my repo settings at pages/deploy from a branch and choose `prod`. Example [HERE](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) 

After doing that, I deployed my site and the error would be fixed.

If you are Ok, I can defo raise a PR to update the FAQs and add the workaround above to help people having this issue.

**Comment by cotes2020** [comment] 2023-04-13 20:09
Hi @danielmacuare The [first section of the FAQ](https://github.com/cotes2020/jekyll-theme-chirpy/wiki/FAQ#why-is-there-a-blank-page-after-the-website-is-deployed-to-github-pages) is about the solution to this issue. More thant 90% of the scenarios, users submit issues without reading the docs. 

But your case is a bit special because you are using a new branch `prod`, but this was mentioned in "Getting Started" in an older version, and then removed because the `main/master` branch was not expected to be modified.

**Comment by cotes2020** [comment] 2023-04-13 20:18
@danielmacuare and the snapshot as follows:

https://github.com/cotes2020/jekyll-theme-chirpy/blob/b1453ccb0c5b269bc867acaaa4f3cc7060df05db/_posts/2019-08-09-getting-started.md?plain=1#L106

**Comment by danielmacuare** [comment] 2023-04-13 20:33
Sorry, I don't want to waste your time I deployed again and I still can see the issue even after changing my branch to `prod`.

I have tried the suggestions in the [deployment section](https://chirpy.cotes.page/posts/getting-started/#deployment) but no joy. I might still be doing something wrong.

My case is a bit special as I'm using a CNAME in Cloudflare blog.dmac.tech to point to ---> danielmacure.github.io

In that case, what I'm doing then is configuring `url` like this:
https://github.com/danielmacuare/danielmacuare.github.io/blob/prod/_config.yml#L30

The weird thing is that the deploy works most of the time (Not talking about github actions but the actual result of the deploy) but sometimes I just commit something, the pipeline runs and deploys, resulting in the error shown in this thread.


I'll keep digging and see if I can find the issue, thanks for your help.

**Comment by cotes2020** [comment] 2023-04-13 20:51
I'm sure Cloudflare is not the root of the issue, if its domain service to gh-pages was down then there would be a lot of complaints all over the internet.

Back to your repository, from the [build logs](https://github.com/danielmacuare/danielmacuare.github.io/actions), it looks like you should not have configured the _source_ of the pages build according to the tutorial (or [GitHub Docs](pages-build-deployment)), because you trigger the default `pages-build-deployment` on every commit. 

Can you paste a screenshot of your repository's pages settings? (Your repo > Settings > Pages > Build and deployment > Source)

**Comment by danielmacuare** [comment] 2023-04-13 21:17
Interesting. That might be the problem then.

It was like this (I changed it at some point while testing):
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/24361228/231884258-19bc441b-8e2c-4b8f-b00a-b400cb0493a9.png">

I have now since a few minutes ago changed it to follow the guide like this:

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/24361228/231884575-bafb26d1-9abb-4cc8-9e32-2cf554b13393.png">


Thanks for the tip I'll try and see if it works fine after a few more commits. I will report back in a few days if the issue is fixed.

**Comment by danielmacuare** [comment] 2023-04-14 12:02
@cotes2020 I can confirm this is working fine for me after changing the Source of my Build and Deployment to Github Actions. Thanks for your help.

**Comment by cotes2020** [comment] 2023-04-14 12:22
@danielmacuare  Ok, will close this issue now.

**Closed by cotes2020** 2023-04-14 12:22 UTC
Labels: duplicate

**Comment by josyulavt** [comment] 2023-10-10 14:56
I fixed this by editing pages-deploy.yml to be: 

```
name: "Build and Deploy"
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

```
