### ISSUE TITLE
Theme Switching Problem in Utterances Due to jQuery Import Order

### ISSUE THREAD

**Issue by Cha0sShi** [cotes2020/jekyll-theme-chirpy#1251] opened 2023-09-19 11:35 UTC
### Checklist

- [X] I'm willing to follow the [Contributing Guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### Describe the bug

I am facing an issue with Utterances where theme switching for dark and light themes is not working as expected. It appears that the problem is related to the order of script imports, specifically, the jQuery library is being imported after the Utterances script.

### Steps To Reproduce

1.Visit the webpage where Utterances is integrated.
2.Try switching between dark and light themes.

### Expected Behavior

The theme should change accordingly when switching between dark and light themes.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy: 

### Anything else?

This issue seems to be specific to the starter version and occurs during the template build process. In contrast, there are no issues with theme switching in the development version. It's possible that there are differences in the build process or configurations between the two versions that might be causing this problem. Further investigation into the build pipeline and dependencies is needed to resolve this issue in the starter version.

**Comment by cotes2020** [comment] 2023-09-19 13:57
Duplicate of #1232

> I'm willing to follow the [Contributing Guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

Please keep your promise, OK?

**Closed by cotes2020** 2023-09-19 13:57 UTC

**Comment by Cha0sShi** [comment] 2023-09-20 05:05
I'm very sorry, I'm a beginner in open source, and I did find a similar issue, but this problem still exists in the 'chirpy-starter' project.
