### ISSUE TITLE
Make home page look like the 'about' page

### ISSUE THREAD

**Issue by pchaubal** [cotes2020/jekyll-theme-chirpy#362] opened 2021-07-12 03:52 UTC
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I want my home page to have a layout like the 'about' page so that the landing page on my site gives some information about me.  How can I do this?

**Comment by cotes2020** [comment] 2021-07-26 05:24
Duplicate of #115

**Closed by cotes2020** 2021-07-26 05:24 UTC
Labels: question
