### ISSUE TITLE
Backend seems to be broken (ALL CHIRPY WEBSITES, EVEN THE DOCUMENTATION ONE IS BROKEN TOO)

### ISSUE THREAD

**Issue by abuturabofficial** [cotes2020/jekyll-theme-chirpy#1720] opened 2024-05-02 05:00 UTC
### Checklist

- [X] I have read and accepted the [contributing guidelines](https://github.com/cotes2020/jekyll-theme-chirpy/blob/master/docs/CONTRIBUTING.md).

### How did you create the site?

Generated from `chirpy-starter`

### Describe the bug

~~I have upgraded from 6.3 to 6.5 couple of days ago. I checked the website, everything was fine.~~

~~Today I opened my website and pages were broken, especially the sidebar and image formatting of the posts.
I did check out the previous working commit locally to see, if it's the update that broke everything, but surprising the website locally was still totally broken.~~

 ~~I don't know what went wrong along the way.~~

Every chirpy website seems to be broken. I have visited the https://chirpy.cotes.page, it's broken too. So, something at the backend has been messed up.

### Steps To Reproduce

~~1. Upgraded to 6.5 from 6.3
2. Used chirpy starter template
3. Website was fine until today~~

### Expected Behavior

The formatting should be as expected.

### Environment

- Ruby: 
- Jekyll: 
- Chirpy: 

```
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
jekyll 4.3.3
jekyll-theme-chirpy (6.5.5)
```

### Anything else?

~~My website: https://cyberfront.me~~

**Comment by abuturabofficial** [comment] 2024-05-02 05:04
![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/68259771/1138c8b6-de0a-4a3b-946b-316b845c62b0)

![image](https://github.com/cotes2020/jekyll-theme-chirpy/assets/68259771/880cbf88-e614-4b3f-b831-3b2e5343abc4)

**Comment by abuturabofficial** [comment] 2024-05-02 05:12
Something happening at the backend which broke everything, as I can see the chirpy documentation sites is broken too.

**Comment by abuturabofficial** [comment] 2024-05-02 05:15
I had to revise my notes and this happened :)

**Comment by kungfux** [comment] 2024-05-02 06:48
Duplicate of #1718

**Closed** 2024-05-02 06:49 UTC
Labels: duplicate
