### ISSUE TITLE
I tried adding the jemoji gem, but wrapping is strange

### ISSUE THREAD

**Issue by alexandra-zaharia** [cotes2020/jekyll-theme-chirpy#204] opened 2020-12-12 00:56 UTC
## Checklist

- [x] I have read the [tutorials](https://chirpy.cotes.info/categories/tutorial/) and know the correct effect of the functional design.
- [x] There are no similar question on existing issues (including closed ones).
- [x] I searched the Internet for related problems, but still couldn't solve it.
- [x] My question is based on the latest code of `master` branch.

## Description

I've added [jemoji](https://github.com/jekyll/jemoji) locally. It works but smileys are far off from the text:

![jemoji](https://user-images.githubusercontent.com/7894916/101967538-3079bc00-3c1b-11eb-9bcc-2c5a0d74c1ef.png)

What the post contains in markdown is:

```
And we're done! :smiley: (Why is that smiley so far off? :suspect:)
```

The generated HTML is (I edited out the links for brevity):

```html
<p>
  And we’re done! 
  <img class="emoji" title=":smiley:" alt=":smiley:" src="..." height="20" width="20"> 
  (Why is that smiley so far off? 
  <img class="emoji" title=":suspect:" alt=":suspect:" src="..." height="20" width="20">)
</p>
```

Now, my HTML and CSS kung-fu is very low, but I can't help but wonder whether it's a side effect of text wrapping around images (I mean the configurable size and alignment as shown in the demo post "Text and typography"). Do you think a special treatment could be applied to `img` tags from the `emoji` class, allowing them to flow nicely along the text?

**Comment by cotes2020** [comment] 2020-12-12 09:46
I've found the cause: it's the CSS stuff, and will be fixed soon :)

**Comment by alexandra-zaharia** [comment] 2020-12-12 14:27
Great, thank you very much! :+1:

**Closed** 2020-12-12 16:44 UTC
Labels: question
